openapi: 3.0.1
info:
  title: API de Produtos
  version: 1.0.0
servers:
- url:  http://api
  description: 
paths:
  /categories:
    get:
      summary: Lista de categorias
      responses:
         200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
          404:
           description: Especialidade não encontrada
           content:
            application/json:
              example: "Not Found" 
  /categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Recupera uma Categoria pelo ID
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        404:
          description: Especialidade não encontrada
          content:
            application/json:
              example: "Not Found"      
  /admin/categories:
    post:
      summary: Cria nova Categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
